"""empty message

Revision ID: a3a41c5782e2
Revises: 99e7a036e356
Create Date: 2025-12-24 17:00:05.263641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a3a41c5782e2'
down_revision: Union[str, Sequence[str], None] = '99e7a036e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gatewayconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gatewayconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gatewayconfig_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gatewayconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gatewayconfig_name'))

    op.drop_table('gatewayconfig')
    # ### end Alembic commands ###
